skydoves/Balloon

- README.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
What types of changes does your code introduce?
Ensure your change is properly formatted by running:
```gradle
$ ./gradlew spotlessApply
```
Please correct any failures before requesting a review.
> fixed small typo error

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
What types of changes does your code introduce?
Ensure your change is properly formatted by running:
```gradle
$ ./gradlew spotlessApply
```
Please correct any failures before requesting a review.
> initializeBackground: Remove repeated instruction

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Refactor show and relayShow functionalities for receiving xOff and yOff parameter default
> Refactor show and relayShow functionalities for receiving xOff and yOff parameter default

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonHighlightAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonLazyExtension.kt
- balloon/src/main/java/com/skydoves/balloon/FragmentBalloonLazy.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/ContextExtension.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonOverlayShape.kt
- balloon/src/main/res/anim/heartbeat_bottom_balloon_library.xml
- balloon/src/main/res/anim/heartbeat_center_balloon_library.xml
- balloon/src/main/res/anim/heartbeat_left_balloon_library.xml
- balloon/src/main/res/anim/heartbeat_right_balloon_library.xml
- balloon/src/main/res/anim/heartbeat_top_balloon_library.xml
Hello my friend,
thank you for the great library I started using in my project. Here are a few changes I needed to make for my project.
1. during lazy initialization in the fragment I want to get a non-null object
2. I want some animation after displaying a balloon
3. I want to adjust the size of the elements using dimensions
I'm sending this pull request if you think some of these changes/implementations can be used in the library
> highlight anim, dimension params, lazy init in fragment

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Change isShowing property after checking preferences. (#168)
> Change isShowing property after checking preferences

- README.md
- app/src/main/java/com/skydoves/balloondemo/BalloonUtils.kt
- app/src/main/java/com/skydoves/balloondemo/factory/CustomListBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/EditBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/ProfileBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/ViewHolderBalloonFactory.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/TextViewExtension.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextView.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextViewParams.kt
- dependencies.gradle
The previous `isRtlSupport` method is removed and rtl will be applied automatically based on the local rtl layout settings.
> Feature: Rtl support for VectorTextView

- app/src/main/java/com/skydoves/balloondemo/factory/ProfileBalloonFactory.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Invoke dismiss() instead of the onDestroy() on Pause lifecycle event #184
> Invoke dismiss() instead of the onDestroy() on Pause lifecycle event

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Implement vertical & horizontal related functions.
- setPaddingHorizontal()
- setPaddingVertical()
- setMarginHorizontal
- setMarginVertical
> Implement vertical & horizontal related functions

- app/src/main/java/com/skydoves/balloondemo/factory/ViewHolderBalloonFactory.kt
- app/src/main/res/values/dimens.xml
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/IconForm.kt
- balloon/src/main/java/com/skydoves/balloon/TextForm.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/ContextExtension.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/NumberExtension.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- balloon/src/main/java/com/skydoves/balloon/radius/RadiusLayout.kt
Refactor: dp inline extensions.
> Refactor: dp inline extensions

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Move the post runner inside of the if-conditional and check the view is attached on the window or not using the `isAttachedToWindow`.
#192
> Move post runner inside of the if conditional and check isAttachedToWindow

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Me again, 
I wanted to use the relay function with showCount, but like been mentioned in issue #105 there is a problem since we don't save the next Balloon. As a workaround I want to add a function to check if the balloon should show up or not, making it easier to check it 😄
> Add check to see if balloon should show up

- balloon/src/main/java/com/skydoves/balloon/AutoDismissRunnable.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
> Fix: Auto dismiss (#210)

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
Fix overlay padding units (#212).
> Fix overlay padding units (#212)

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
Hello there, here comes another pull request from me :) This one makes it possible to add a color to the overlay padding, which was requested in issue #213. I added a picture of an example of how it looks! 
Have a great day!
> Making it possible to add a color to the overlay padding

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/ContextExtension.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/SizeExtension.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/TextViewExtension.kt
> Refactor: SizeExtensions

- balloon/api/balloon.api
- balloon/build.gradle
- balloon/src/main/java/com/skydoves/balloon/extensions/GlobalExtension.kt
- build.gradle
- dependencies.gradle
> Integrate: Binary Validator

- .github/workflows/android.yml
Update GitHub Actions workflows.
> Update GitHub Actions workflows

- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Make public of bodyWindow and overlayWindow.
> Make public of bodyWindow and overlayWindow

- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/GlobalExtension.kt
A new feature: isAttachedInDecor
> Feature: isAttachedInDecor

- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonPersistence.kt
Implement clearAllPreferences.
> Implement clearAllPreferences

- app/build.gradle
- app/src/main/AndroidManifest.xml
- balloon/build.gradle
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
> Upgrade AGP to 7.0.2

- app/src/main/java/com/skydoves/balloondemo/factory/ProfileBalloonFactory.kt
- app/src/main/res/layout/item_custom.xml
- app/src/main/res/layout/layout_custom_list.xml
- balloon/src/main/java/com/skydoves/balloon/radius/RadiusLayout.kt
Fix: RadiusLayout's radius receives px values instead of the dp/ (#220)
> Fix: RadiusLayout's radius receives px values instead of the dp

- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/ContextExtension.kt
Refactor: arrowHalfSize property.
> Refactor: arrowHalfSize property

- README.md
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
> Update README documentations

- app/src/main/java/com/skydoves/balloondemo/factory/EditBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonHighlightAnimation.kt
- balloon/src/main/res/anim/shake_bottom_balloon_library.xml
- balloon/src/main/res/anim/shake_left_balloon_library.xml
- balloon/src/main/res/anim/shake_right_balloon_library.xml
- balloon/src/main/res/anim/shake_top_balloon_library.xml
Feature: highlight-animations.
> Feature: highlight-animations

- app/src/main/java/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonHighlightAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotationAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotationDirection.kt
A new feature: `BalloonRotationAnimation`.
> Feature: BalloonRotationAnimation

- app/src/main/java/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonHighlightAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotateAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotateDirection.kt
Change classes name of the rotation animations.
> Change classes name of the rotation animations

- README.md
- gradle.properties
Update Readme and prepare for the next release.
> Update Readme and prepare for the next release

- .editorconfig
- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/ActivityBalloonLazy.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/FragmentBalloonLazy.kt
- dependencies.gradle
- editorconfig
Feature: Migrate to lifecycle [2.4.0](https://developer.android.com/jetpack/androidx/releases/lifecycle).
> Feature: Migrate to lifecycle 2.4.0

- balloon/build.gradle
- balloon/src/main/java/com/skydoves/balloon/ArrowOrientation.kt
- balloon/src/main/java/com/skydoves/balloon/ArrowOrientationRules.kt
- balloon/src/main/java/com/skydoves/balloon/ArrowPositionRules.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonCenterAlign.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonExtension.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonHighlightAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonLazyExtension.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonPersistence.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonSizeSpec.kt
- balloon/src/main/java/com/skydoves/balloon/IconForm.kt
- balloon/src/main/java/com/skydoves/balloon/IconGravity.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonClickListener.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonDismissListener.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonInitializedListener.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonOutsideTouchListener.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonOverlayClickListener.kt
- balloon/src/main/java/com/skydoves/balloon/TextForm.kt
- balloon/src/main/java/com/skydoves/balloon/ViewBalloonLazy.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotateAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/animations/BalloonRotateDirection.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BallonOverlayAnimation.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonOverlayShape.kt
- balloon/src/main/java/com/skydoves/balloon/radius/RadiusLayout.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextView.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextViewParams.kt
> Apply explicit mode

- balloon/build.gradle
- balloon/src/main/java/com/skydoves/balloon/extensions/GlobalExtension.kt
- dependencies.gradle
Add androidx annotations to check API version.
> Add androidx annotations to check API version

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Check if the layout has any parent view. (#281)
> Check if the layout has any parent view

- balloon/src/main/kotlin/com/skydoves/balloon/internal/ViewBalloonLazy.kt
Check `LifecycleOwner` by using `findViewTreeLifecycleOwner`.
> Check LifecycleOwner by using findViewTreeLifecycleOwner

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Implement canShowBalloonWindow and check anchor is attached in the post. Related: #280
> Implement canShowBalloonWindow and check anchor is attached in the post

- README.md
- app/src/main/kotlin/com/skydoves/balloondemo/factory/CustomListBalloonFactory.kt
> Improve README

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Implement setLayout method with ViewBinding.
> Implement setLayout method with ViewBinding

- balloon/src/main/kotlin/com/skydoves/balloon/BalloonLazyExtension.kt
Implement balloon extension for `ViewBinding` to initialize lazy property.
> Implement balloon extension for ViewBinding to initialize lazy property

- balloon/api/balloon.api
- dependencies.gradle
> Bump kotlin to 1.5.31

- app/src/main/res/layout/toolbar_custom.xml
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Refactor AppCompat TextView and ImageView
> Refactor AppCompat TextView and ImageView

- dependencies.gradle
Bump Kotlin to `1.5.32`. (#307)
> Bump Kotlin to 1.5.32

- balloon/src/main/res/layout/balloon_layout_body.xml
Use srcCompat on the `balloon_layout_body` layout.
> Use srcCompat on the balloon_layout_body layout

- dependencies.gradle
update the version of gradleBuildTool from 7.1.0 to 7.1.2
Actually, it's the first time in my life that I've contributed(?) to open source. Is this also possible to pr?
감사합니다!
> update the version of gradleBuildTool from 7.1.0 to 7.1.2

- app/src/main/kotlin/com/skydoves/balloondemo/CustomActivity.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- dependencies.gradle
Implement multiple overlay views.
> Implement multiple overlay views

- dependencies.gradle
Bump maven and spotless versions.
> Bump maven and spotless versions

- app/src/main/kotlin/com/skydoves/balloondemo/CustomActivity.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonAlign.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonCenterAlign.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonExtension.kt
New Feature: **showAlign** method and extension.
> New Feature: showAlign method and extension

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/ArrowOrientation.kt
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Support RTL layout for the arrow orientation.
> Support RTL layout for the arrow orientation

- gradle.properties
> Cleanup Gradle properties

- app/src/main/kotlin/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- gradle.properties
Set **nonTransitiveRClass** property as `true`.
> Set nonTransitiveRClass property as true

- balloon/build.gradle
- gradle.properties
Configure Gradle environments.
> Configure Gradle environments

- balloon/build.gradle
Add publishing DSL with singleVariant.
> Add publishing DSL with singleVariant

- app/build.gradle
- balloon/build.gradle
- build.gradle
- buildSrc/src/main/kotlin/com/skydoves/balloon/Configuration.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
- scripts/publish-root.gradle
> Update buildSrc package name

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove the registered observer on onDestroy lifecycle.
> Remove the registered observer on onDestroy lifecycle

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/ArrowOrientation.kt
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove deprecated Left and Right arrow orientations.
> Remove deprecated Left and Right arrow orientations

- buildSrc/src/main/kotlin/com/skydoves/balloon/Configuration.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
Update compile and target SDK to 32.
> Update compile and target SDK to 32

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- balloon/src/main/kotlin/com/skydoves/balloon/overlay/BalloonOverlayShape.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
Implement BalloonOverlayEmpty.
> Implement BalloonOverlayEmpty

- build.gradle
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
> Bump Kotlin to 1.7.0

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Add the possibility to change overlay window gravity (#347).
> Add the possibility to change overlay window gravity (#347)

- app/src/main/kotlin/com/skydoves/balloondemo/CustomActivity.kt
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/animations/BalloonRotateAnimation.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/SizeExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
- balloon/src/main/kotlin/com/skydoves/balloon/radius/RadiusLayout.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
- spotless/spotless.gradle
Update AGP and dependencies version.
> Update AGP and dependencies version

- balloon/src/main/res/layout/balloon_layout_body.xml
Replace AppCompatImageView to ImageView for the arrow.
> Replace AppCompatImageView to ImageView for the arrow

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/GlobalExtension.kt
Check API level with isAPILevelHigherThan23 before setting foreground the arrow/ (#354)
> Check API level with isAPILevelHigherThan23 before setting foreground the arrow

- balloon/src/main/kotlin/com/skydoves/balloon/extensions/ViewExtension.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Configuration.kt
- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
Update AGP to 7.3.0 and target SDK to 33.
> Update AGP to 7.3.0 and target SDK to 33

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/TextForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
Allow setting text line spacing (#376)
> Allow setting text lineSpacing Extra

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/IconForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/TextForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/StringExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/vectortext/VectorTextViewParams.kt
Allow setting ContentDescription for the balloon icon.
> Allow setting ContentDescription for the balloon icon

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/IconForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/vectortext/VectorTextViewParams.kt
Change `iconContentDescription` type from `String` to `CharSequence`.
> Change iconContentDescription type to CharSequence

- balloon/src/main/baseline-prof.txt
- benchmark-app/build.gradle.kts
- benchmark/build.gradle.kts
- buildSrc/src/main/kotlin/com/skydoves/balloon/Configuration.kt
Update baseline profiles for balloon.
> Update baseline profiles for balloon

- README.md
- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
Update README for Jetpack Compose.
> Update README for Jetpack Compose

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Update anchor view's size with onSizeChanged (#399)
> Update anchor view's size with onSizeChanged

- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonComposeView.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonWindow.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Refactor measuring ways for the width composable content size.
> Refactor measuring ways for the width composable content size

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Add rules for the start and end arrow position of ALIGN_ANCHOR. (#397)
> Add rules for the start and end arrow position of ALIGN_ANCHOR

- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Fix Compose balloon content measurement systems with density. (#399)
> Fix Compose balloon content measurement systems with density

- gradle/libs.versions.toml
> Bump AGP to 7.4.0

- app/build.gradle.kts
- balloon-compose/build.gradle.kts
- benchmark-app/build.gradle.kts
- gradle/libs.versions.toml
> Migrate to Compose BOM

- README.md
- app/build.gradle.kts
- app/src/main/res/layout/layout_custom_profile.xml
- app/src/main/res/layout/layout_custom_tag.xml
- app/src/main/res/layout/toolbar_custom.xml
- balloon-compose/build.gradle.kts
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/GlobalExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/ViewExtension.kt
- balloon/src/main/res/layout/balloon_layout_body.xml
- benchmark-app/build.gradle.kts
- buildSrc/src/main/kotlin/com/skydoves/balloon/Configuration.kt
Increment min SDK from 17 to 21. (#412)
> Increment min SDK from 17 to 21

- balloon/src/main/kotlin/com/skydoves/balloon/internals/FragmentBalloonLazy.kt
Hi. I refactored make the cached value early returned when it is not null. If you don't like it, please close it.
> Refactored make the cached value early returned when it is not null

- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/RememberBalloonBuilder.kt
Implement rememberBalloonWindow.
> Implement rememberBalloonWindow

- balloon/src/main/kotlin/com/skydoves/balloon/internals/ActivityBalloonLazy.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/FragmentBalloonLazy.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/ViewBalloonLazy.kt
Migrate to getDeclaredConstructor from newInstance.
> Migrate to getDeclaredConstructor from newInstance

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove cleaning balloon channel consumer on destroy lifecycle.
> Remove cleaning balloon channel consumer on destroy lifecycle

- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
- balloon-compose/api/balloon-compose.api
- balloon-compose/build.gradle.kts
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/AwaitBalloonWindows.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonComposeView.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonWindow.kt
- balloon/api/balloon.api
- balloon/build.gradle.kts
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonCenterAlign.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonPlacement.kt
- balloon/src/main/kotlin/com/skydoves/balloon/DeferredBalloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/DeferredBalloonGroup.kt
- balloon/src/main/kotlin/com/skydoves/balloon/PlacementType.kt
- balloon/src/main/kotlin/com/skydoves/balloon/annotations/InternalBalloonApi.kt
Compose: Implement AwaitBalloonWindows.
> Compose: Implement AwaitBalloonWindows

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/Definition.kt
Use popup for measuring balloon content layout.
> Use popup for measuring balloon content layout

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Fix duplicated arrow size was applied to the balloon content. (#499)
> [Compose] Fix duplicated arrow size was applied to the balloon content

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/TextForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
Support setting includeFontPadding for the default text.
> Support setting includeFontPadding for the default text

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Invoke previous onDismissListener for relay and await balloon
> Invoke previous onDismissListener for relay and await balloon

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Implement setDismissWhenTouchMargin.
> Implement setDismissWhenTouchMargin

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Implement onComposedAnchor and onBalloonWindowInitialized.
> Implement onComposedAnchor and onBalloonWindowInitialized

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonWindow.kt
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove the constraints for measuring the composable content.
> Remove the constraints for measuring the composable content

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Fix overwriting the arrow orientation rules.
> Fix overwriting the arrow orientation rules

- .editorconfig
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonPlacement.kt
Implement width/height properties for updating the body window. Resolve #581
> Implement width/height properties for updating the body window

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Remove initializing global positioning and offsets. #586
> Remove initializing global positioning and offsets

- .gitignore
- app/build.gradle.kts
- balloon-compose/build.gradle.kts
- benchmark-app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
Migrate to Kotlin 2.0 and Compose Compiler plugin.
> Migrate to Kotlin 2.0 and Compose Compiler plugin

- balloon-compose/build.gradle.kts
- balloon/build.gradle.kts
> Use new compiler options

- balloon/src/main/resources/META-INF/com/github/skydoves/balloon/verification.properties
Add verification.properties META info.
> Add verification.properties META info

- gradle/libs.versions.toml
> Bump Kotlin to 2.0.20

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove the elevation paddings (#587)
> Remove the elevation paddings

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
Implement setOverlayPaddingShader builder method (#672)
> Implement setOverlayPaddingShader builder method

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Check if the anchor view's window token is valid.
> Check if the anchor view's window token is valid

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Dispatch the move and up events to the anchor view. (#713)
> Dispatch the move and up events to the anchor view

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
- gradle/libs.versions.toml
Fix the widthRatio doesn't calculate properly in Compose. (#721)
> Fix the widthRatio doesn't calculate properly in Compose

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Hide popup in the local inspection mode.
> Hide popup in the local inspection mode

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Fix NPE issue for checking the isBinderAlive.
> Fix NPE issue for checking the isBinderAlive

- README.md
Docs: fix mis-leading the alignment (#743)
> Docs: fix mis-leading the alignment

- balloon/build.gradle.kts
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Remove stable marker dependency on the balloon. (#727)
> Remove stable marker dependency on the balloon

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Fix behaviors for setShouldPassTouchEventToAnchor (#728)
> Fix behaviors for setShouldPassTouchEventToAnchor

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Fix max width size limitation (#738)
> Fix max width size limitation

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Fix measuring text width size to limit with displayWidth.
> Fix measuring text width size to limit with displayWidth

- balloon/build.gradle.kts
- balloon/consumer-rules.pro
Add proguard rules for preventing obfuscation the Balloon.Builder's constructors. #773
> Add proguard rules for preventing obfuscation the Balloon.Builder's constructors

- gradle/libs.versions.toml
> Bump Kotlin to 2.1.10

- README.md
> Docs: fix typos

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Rollback adding the padding values for the elevation.
> Rollback adding the padding values for the elevation

- balloon/src/main/kotlin/com/skydoves/balloon/internals/FragmentExtensions.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/ViewBalloonLazy.kt
- gradle/libs.versions.toml
Remove fragment-ktx dependency and use fragment dependency.
> Remove fragment-ktx dependency and use fragment dependency
