skydoves/Balloon

- app/src/main/java/com/skydoves/balloondemo/MainActivity.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonClickListener.kt
- balloon/src/main/java/com/skydoves/balloon/OnBalloonOutsideTouchListener.kt
I have a use case where I need a reference to the touched view  & location
OnBalloonOutsideTouchListener#onBalloonOutsideTouch() & OnBalloonClickListener#onBalloonClick() is changed
> Pass down View & MotionEvent to listeners

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
If the option `dismissWhenTouchOutside` is true and when the ballon content is just touched, but not clicked yet, the balloon dismisses. So I suggest to move the dismiss into the if block where  event.action is checked for MotionEvent.ACTION_OUTSIDE.
> dismissing when the dialog touched (but not clicked) fixed

- app/src/main/java/com/skydoves/balloondemo/CustomActivity.kt
- app/src/main/java/com/skydoves/balloondemo/factory/ProfileBalloonFactory.kt
- app/src/main/java/com/skydoves/balloondemo/factory/TagBalloonFactory.kt
- app/src/main/res/layout/activity_custom.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/item_custom.xml
- app/src/main/res/layout/layout_custom_list.xml
- app/src/main/res/layout/layout_custom_profile.xml
- app/src/main/res/layout/layout_custom_tag.xml
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/Definition.kt
- balloon/src/main/res/layout/layout_balloon.xml
- dependencies.gradle
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
What types of changes does your code introduce?
Wrap content & padding instead of height/width dp.
> Resolve #1 Support wrap content & padding instead of height/width dp

- README.md
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
I was using your library and came across a crash. Here are the steps to reproduce:
1. Create 2 or more balloons
2. Connect them using one of the `relay` methods, e.g. `relayShowAlignTop`
3. Make sure to also register a lifecycle owner
4. Make the first balloon show (e.g. from within the activity's `onCreate`)
5. Destroy the activity while the first balloon is shown (e.g. by rotating the device)
This results in a crash because the first balloon is dismissed automatically when the activity is destroyed (via the lifecycle observer), but this triggers the second balloon, which now tries to show up but the activity is already destroyed, leading to a crash.
I have fixed this by adding a field `destroyed` which prevents the relayed balloons from showing up.
I also fixed a few typos in the …
> Fixed crash on relay

- README.md
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/TextForm.kt
- balloon/src/main/java/com/skydoves/balloon/TextViewExtension.kt
This is a new feature that allows setting text
with HTML tags as the tooltip text. This allows
basic formatting like **bold** or _italic_ for the
text inside the tooltip. Defaults to `false`.
> Add support for setting text with HTML tags

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/TextForm.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/TextViewExtension.kt
Library already supports HTML text formatting.
However, in my case, the HTML text also had hyperlinks and I had a requirement to make them clickable.
I've added a var for movementMethod in both Balloon and Textform builders for users to enable this feature by supplying the required MovementMethod by them.
> [Enhancement] Added support for clickable HTML links by exposing the movementMethod attribute of TextView in builders

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
The measured height of the body content is the actual same value as the height of the body window.
But as we can see below its behavior is a little bit different. It seems a bug (PopupWindow).
#171
> Change applying height of the bodyWindow criteria

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
We can set the minimum and maximum width size of the balloon when the width size is `BalloonSizeSpec.WRAP`.
> Feature: minWidth and maxWidth

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Implemented missing `setOnBalloonInitializedListener` in the `Balloon` class.
> Feature: setOnBalloonInitializedListener

- app/src/main/java/com/skydoves/balloondemo/factory/ViewHolderBalloonFactory.kt
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/IconGravity.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/TextViewExtension.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextView.kt
- balloon/src/main/java/com/skydoves/balloon/vectortext/VectorTextViewParams.kt
- balloon/src/main/res/values/attrs.xml
To support RTL about the icon gravity, the previous enum type of the `IconGravity.LEFT` and `IconGravity.RIGHT` will be deprecated.
And we can use a new `IconGravity.START` and `IconGravity.END`.
> Deprecate IconGravity.LEFT and IconGravity.RIGHT

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/extensions/DrawableExtension.kt
Ensures the minimum height size of the TextView for the compound drawable. #171
> Fix: min height size of the TextView

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Implemented a new feature where the default arrow can match the background of the balloonCard. This is done mainly to support a gradient background where the arrow will follow the gradient of the balloonCard.
Does not work with custom arrows. The arrow must also be constrained to the borders of the balloonCard to fetch the correct colours. 
In response to Issue #88 
What types of changes does your code introduce?
> [Enhancement] Added support for gradient colors on the default arrow

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Thanks for a great lib, I needed to introduce one small addition to the lib for one of my projects. 
I added the possibility to add an onTouchListener to the overlay making it possible to pass MotionEvents other than ACTION_OUTSIDE down to the anchor. 
Hopefully this is something that is of interest to add to the lib.
> Added onTouchListener option to the overlay popup

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Add setOnBalloonOverlayTouchListener using a lambd.
> Add setOnBalloonOverlayTouchListener using a lambda

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Hope everything is good :) Got some more additions I would like to add. These additions makes it possible to add a min and max ratio, which works just like the min and max for pixels but with ratio instead. I also fixed so it should work with the new text measuring  implementation.
> Add minimum and maximum ratio for the Balloon

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Hi again, I found a bug in my addition of min and max ratio where I used the measuredWidth from the binding instead of the parameter passed to the getMeasuredTextWidth function. That went right past my testing and just noticed it when I forgot to add a minWidthRatio. Sorry for this!
> Bug fix where wrong reference were used in getMeasuredTextWidth

- app/src/main/java/com/skydoves/balloondemo/factory/EditBalloonFactory.kt
- app/src/main/res/values/dimens.xml
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
The implementation for the feature request https://github.com/skydoves/Balloon/issues/213 (PR https://github.com/skydoves/Balloon/pull/221) exhibits an issue if a semitransparent color is used for overlay padding:
This is because Paint stoke is always centered, so half of the stroke width is drown inside and the second half is drown outside.
The goal is to use only the inside half of the stroke (which is not directly supported by Android). This PR emulates inner stroke for the padding, thus not overstepping the actual padding:
* No custom color for overlay padding:
* Opaque custom color for overlay padding:
* Semitransparent color for overlay padding:
This is a fix for the PR https://github.com/skydoves/Balloon/pull/221.
> fixes drawing the overlay padding rectangle

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/overlay/BalloonAnchorOverlayView.kt
> Fixes #228 "Overlay is not redrawn on Balloon.update(anchor) call"

- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
Hi again, I found an inconsistency in the code that I wrote in #214. In getMeasuredTextWidth I used _coerceIn_ instead of _coerceAtMost_ which is more consistent with how the other cases is written. The subtraction of spaces outside of the _coerceIn_-function gave some unwanted behavior where the dialog would be smaller than intended
> Fix min max ratio inconsistency in getMeasuredTextWidth

- balloon/api/balloon.api
- balloon/src/main/java/com/skydoves/balloon/Balloon.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonCenterAlign.kt
- balloon/src/main/java/com/skydoves/balloon/BalloonExtension.kt
* Shows the balloon over the anchor view (overlap) as the center aligns.
* Even if you use with the [ArrowOrientationRules.ALIGN_ANCHOR], the alignment will not be guaranteed.
* So if you use the function, use with [ArrowOrientationRules.ALIGN_FIXED] and fixed [ArrowOrientation].
*
* @param anchor A target view which popup will be shown with overlap.
* @param xOff A horizontal offset from the anchor in pixels.
* @param yOff A vertical offset from the anchor in pixels.
* @param centerAlign A rule for deciding the alignment of the balloon.
> Feature: showAtCenter

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonLazyExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/IconGravity.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
Removed deprecated functions since `1.3.8`.
> Remove deprecated functions since 1.3.8

- buildSrc/src/main/kotlin/com/skydoves/balloon/Dependencies.kt
Bump AGP to 7.2.0 and kotlin to 1.6.21.
> Bump AGP to 7.2.0 and kotlin to 1.6.21

- balloon/src/main/kotlin/com/skydoves/balloon/vectortext/VectorTextView.kt
Fix getting resource id from the drawable tint color.
> Fix getting resource id from the drawable tint color

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/GlobalExtension.kt
Implement runOnAfterSDK23 and fix lint errors.
> Implement runOnAfterSDK23 and fix lint errors

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/res/layout/balloon_layout_body.xml
The goal of this PR is to improve the correctness of screen reader hints for Balloons that do not have a click listener set (via `Balloon::setOnBalloonClickListener`).
Currently, Talkback will incorrectly say "double-tap to activate" for these Balloons. This change removes that part of the Talkback description without affecting the rest of it.
Currently `setOnBalloonClickListener()` always sets a "wrapper/parent" click listener on the Balloon, even when the click listener argument is `null`. Talkback incorrectly infers from this that the Balloon is clickable, despite it possibly being a no-op click listener.
This change only sets the parent click listener when clicking would likely have some noticeable effect. More specifically, if the `onBalloonClickListener` argument is non-null or if …
> A11y fix: remove clickable hint from Talkback description when no click listener is set on Balloon

- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/RememberBalloonBuilder.kt
Fix issue https://github.com/skydoves/Balloon/issues/475
Ensure your change is properly formatted by running:
```bash
$ ./gradlew spotlessApply
```
Then dump binary APIs of this library that is public in sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that makes this change binary incompatible.
```bash
./gradlew apiDump
```
> Add optional key into rememberBalloonBuilder

- README.md
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/BalloonExtension.kt
Alternative for relay methods, that allows to make complex logic easier to implement
There's static channel in Balloon class to ensure sequential work. When a popup is displayed, channel waits until it gets dismissed and only then display next balloon.
> Add Coroutine API for sequential popups displaying

- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonComposeView.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonWindow.kt
Implement await shows balloon for Compose.
> Implement await shows balloon for Compose

- README.md
- app/src/main/kotlin/com/skydoves/balloondemo/AlignmentActivity.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/AwaitBalloons.kt
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/DeferredBalloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/DeferredBalloonGroup.kt
Add API to display more than one balloon within sequence.
Added `awaitBalloons` function with Kotlin DSL 
```
lifecycleScope.launch {
// shows balloons at the same time
awaitBalloons {
// dismissing of any balloon dismisses all of them. Default behaviour
dismissSequentially = false
textView.alignTop(balloonAlignTop)
textView.alignStart(balloonAlignStart)
textView.alignEnd(balloonAlignEnd)
textView.alignBottom(balloonAlignBottom)
}
// shows another group after dismissing the previous group.
awaitBalloons {
dismissSequentially = true // balloons dismissed individually
imageView.alignTop(balloonAlignTop)
imageView.alignStart(balloonAlignStart)
imageView.alignEnd(balloonAlignEnd)
imageView.alignBottom(balloonAlignBottom)
}
}
```
> Parallel balloons displaying with Coroutines API

- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/TextForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
Add letter spacing to the API.
All changes are essentially a copy of the line spacing code, changed to letter spacing.
Simply adding a `.setTextLetterSpacing(0.1f)` can result in improved readability in text:
Ensure your change is properly formatted by running:
```bash
$ ./gradlew spotlessApply
```
:no_entry: — This fails already in the main library itself
Then dump binary APIs of this library that is public in sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that makes this change binary incompatible.
```bash
./gradlew apiDump
```
:heavy_check_mark: 
Please correct any failures before requesting a review.
All submissions, including submissions by project members, require review. We use GitHub pull requests for this purpose. Consult [GitHub …
> Add a letter spacing option for Balloon and TextForm.

- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt
Fix the device restart that occurs on devices running Android 9 and below when showing a Balloon with Compose content.
Fixes #528 and #531
For some reason, passing an offset with Int.MAX_VALUE to the Compose Popup causes the device to become unresponsive and restart on older Android versions. Removing the offset from the popup doesn't seem to affect the position of the final balloon, so removing the offset seems to be a safe fix.
> Remove offset on popup for Compose balloons

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
minPosition and maxPosition are randomly chosen so they don't always give correct results. Here we tried to solve on edge case as noted in issue: [#413](https://github.com/skydoves/Balloon/issues/413)
Hello I am Nika, I have been using this library for quite some time, I wanted to help in some way.
This is my first PR to public repo, I am new to Open source contribution, please feel free to provide any criticism that can improve this PR or my abilities, thank you.
Goal of this PR is to solve arrow positioning issues such as [#413](https://github.com/skydoves/Balloon/issues/413)
For now only a certain edge case that was in issue[#413](https://github.com/skydoves/Balloon/issues/413) has been fixed. Logic seems to be quite complicated. We will have to calculate size of the balloon, size of …
> Change arrow positioning logic for ArrowPositionRules.ALIGN_ANCHOR

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Touching outside the balloonWrapper should dismiss the PopupWindow. This should help with the issue: [486](https://github.com/skydoves/Balloon/issues/486). This is not the finished product but a work in progress.
`if (event.action == MotionEvent.ACTION_UP) {`
`            if(binding.balloonWrapper.getViewPointOnScreen().x > event.rawX) {`
`              if (builder.dismissWhenTouchOutside) {`
`                this@Balloon.dismiss()`
`              }`
`              onBalloonOutsideTouchListener?.onBalloonOutsideTouch(view, event)`
`              return true`
`            }`
`          }`
If the user touches to the left of the balloonWrapper Balloon will be dismissed. This solves the issue for the left margin, but other margins should also be considered. The code is not fully polished …
> Touching outside the balloonWrapper should dismiss the Balloon(PopupWindow)

- app/src/main/kotlin/com/skydoves/balloondemo/ComposeActivity.kt
- balloon-compose/api/balloon-compose.api
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonComposeView.kt
- balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/BalloonWindow.kt
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Implement update relevant methods.
> Implement update relevant methods

- balloon/build.gradle.kts
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- gradle/libs.versions.toml
Make stable for balloon builder and factory.
> Make stable for balloon builder and factory

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
Resolved missing horizontal padding when calculating width for custom layouts.
When showing a Balloon with a custom layout, the [custom view tree is walked](https://github.com/skydoves/Balloon/blob/main/balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt#L1915) and checked for instances of `TextView`.
Any `TextView` widgets, and by extension, descendants of `TextView` (e.g., `Button`), has its [text measured for calculating width](https://github.com/skydoves/Balloon/blob/main/balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt#L1896).
The measurement heuristics adds horizontal padding while using compound drawables, but not otherwise. This works great when a custom layout's `TextView` has no horizontal padding, but constrains text when horizontal padding is present.
Since padding …
> Update custom view width calculation for TextViews

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/ContextExtension.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/FragmentBalloonLazy.kt
- balloon/src/main/kotlin/com/skydoves/balloon/internals/ViewBalloonLazy.kt
Previously if we create a fragment that is not yet attached to the activity and reference the balloon, this will throw an `IllegalStateException`. This is because the lazy loader requires an `Activity` even thought the implementation only requires `Context`.
This change removes all references to activities, so the balloon can be successfully attached to the anchor without needing the activity context. 
1. Update Lazy helpers to use `requireContext` instead of `requireActivity`
2. Remove unused `getActivity` method 
3. Remove unneccesary `Context.isFinishing` method because `isAttachedToWindow` should resolve issue #92 
All submissions, including submissions by project members, require review. We use GitHub pull requests for this purpose. Consult [GitHub …
> Support detached Fragments by removing references to the Activity

- README.md
- balloon/api/balloon.api
- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
- balloon/src/main/kotlin/com/skydoves/balloon/TextForm.kt
- balloon/src/main/kotlin/com/skydoves/balloon/extensions/TextViewExtension.kt
You can set auto-sized text based on the balloon's window size, specifying minimum and maximum text sizes, as shown in the example below:
```kotlin
.setTextSize(15f)
.setMinAutoSizeTextSize(14f)
.setMaxAutoSizeTextSize(18f)
.setEnableAutoSized(true)
```
> Note: Ensure that the maximum auto text size is set to a value higher than the minimum auto text size.
> Support auto-sized text

- balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt
[Enable isClipArrowEnabled by default by setting setBalloonStroke](https://github.com/skydoves/Balloon/commit/f637fb6f120d97a6ff66168d907e5148ee0abf19).
> Enable isClipArrowEnabled by default by setting setBalloonStroke
